//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeta.EAE.Integrador.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Idioma
    {
        public int Id { get; set; }
        public int IdRegistro { get; set; }
        public string Cultura { get; set; }
        public string Ubicacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Evento Registro { get; set; }
    }
}
