//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeta.EAE.Integrador.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricante
    {
        public Fabricante()
        {
            this.Calendarios = new HashSet<Calendario>();
            this.RegistrosIdiomas = new HashSet<Fabricante_Idioma>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public string IdMarca { get; set; }
    
        public virtual ICollection<Calendario> Calendarios { get; set; }
        public virtual ICollection<Fabricante_Idioma> RegistrosIdiomas { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
