//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeta.EAE.Integrador.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectorsClubEntities : DbContext
    {
        public CollectorsClubEntities()
            : base("name=CollectorsClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calendario> Calendarios { get; set; }
        public DbSet<Calendario_Idioma> Calendarios_Idiomas { get; set; }
        public DbSet<Entidad> Entidades { get; set; }
        public DbSet<Entidad_Idioma> Entidades_Idiomas { get; set; }
        public DbSet<EstadoCalendario> EstadosCalendario { get; set; }
        public DbSet<EstadoCalendario_Idioma> EstadosCalendario_Idiomas { get; set; }
        public DbSet<Fabricante> Fabricantes { get; set; }
        public DbSet<Fabricante_Idioma> Fabricantes_Idiomas { get; set; }
        public DbSet<SubcategoriaCalendario> SubcategoriasCalendario { get; set; }
        public DbSet<SubcategoriaCalendario_Idioma> SubcategoriasCalendario_Idiomas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<CategoriaFoto> CategoriasFotos { get; set; }
        public DbSet<CategoriaFoto_Idioma> CategoriasFotos_Idiomas { get; set; }
        public DbSet<Foto> Fotos { get; set; }
        public DbSet<Foto_Idioma> Fotos_Idiomas { get; set; }
        public DbSet<SolicitudContacto> SolicitudesContacto { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<Video_Idioma> Videos_Idiomas { get; set; }
        public DbSet<Marca> Marcas { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Evento_Idioma> Eventos_Idiomas { get; set; }
        public DbSet<TipoEvento> TiposEvento { get; set; }
        public DbSet<TipoEvento_Idioma> TiposEvento_Idiomas { get; set; }
        public DbSet<CategoriaCalendario> CategoriasCalendario { get; set; }
        public DbSet<CategoriaCalendario_Idioma> CategoriasCalendario_Idiomas { get; set; }
        public DbSet<TipoColeccionCalendario> TiposColeccionCalendario { get; set; }
        public DbSet<TipoColeccionCalendario_Idioma> TiposColeccionCalendario_Idiomas { get; set; }
    }
}
