//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planeta.EAE.Integrador.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvento
    {
        public TipoEvento()
        {
            this.Eventos = new HashSet<Evento>();
            this.RegistrosIdiomas = new HashSet<TipoEvento_Idioma>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public short Orden { get; set; }
        public string IdMarca { get; set; }
    
        public virtual ICollection<Evento> Eventos { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual ICollection<TipoEvento_Idioma> RegistrosIdiomas { get; set; }
    }
}
