
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using CollectorsClub.Model.Entities;
using CollectorsClub.Model.Configurations;

namespace CollectorsClub.Model { 
	public partial class CollectorsClubEntities : DbContext {
	  public CollectorsClubEntities() : base("name=CollectorsClubEntities") {
			this.Configuration.ProxyCreationEnabled = false;
		}
	
	  protected override void OnModelCreating(DbModelBuilder modelBuilder) {
			modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
			modelBuilder.Configurations.Add(new CalendarioConfiguration());
			modelBuilder.Configurations.Add(new Calendario_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new CategoriaCalendarioConfiguration());
			modelBuilder.Configurations.Add(new CategoriaCalendario_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new CategoriaFotoConfiguration());
			modelBuilder.Configurations.Add(new CategoriaFoto_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new EntidadConfiguration());
			modelBuilder.Configurations.Add(new Entidad_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new EstadoCalendarioConfiguration());
			modelBuilder.Configurations.Add(new EstadoCalendario_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new EventoConfiguration());
			modelBuilder.Configurations.Add(new Evento_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new FabricanteConfiguration());
			modelBuilder.Configurations.Add(new Fabricante_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new FotoConfiguration());
			modelBuilder.Configurations.Add(new Foto_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new MarcaConfiguration());
			modelBuilder.Configurations.Add(new SolicitudContactoConfiguration());
			modelBuilder.Configurations.Add(new SubcategoriaCalendarioConfiguration());
			modelBuilder.Configurations.Add(new SubcategoriaCalendario_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new TipoColeccionCalendarioConfiguration());
			modelBuilder.Configurations.Add(new TipoColeccionCalendario_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new TipoEventoConfiguration());
			modelBuilder.Configurations.Add(new TipoEvento_IdiomaConfiguration());
			modelBuilder.Configurations.Add(new UsuarioConfiguration());
			modelBuilder.Configurations.Add(new VideoConfiguration());
			modelBuilder.Configurations.Add(new Video_IdiomaConfiguration());
		}
	
		public virtual void Commit() {
			base.SaveChanges();
		}
	
	  public DbSet<Calendario> Calendario { get; set; }
	  public DbSet<Calendario_Idioma> Calendario_Idioma { get; set; }
	  public DbSet<Entidad> Entidad { get; set; }
	  public DbSet<Entidad_Idioma> Entidad_Idioma { get; set; }
	  public DbSet<EstadoCalendario> EstadoCalendario { get; set; }
	  public DbSet<EstadoCalendario_Idioma> EstadoCalendario_Idioma { get; set; }
	  public DbSet<Fabricante> Fabricante { get; set; }
	  public DbSet<Fabricante_Idioma> Fabricante_Idioma { get; set; }
	  public DbSet<SubcategoriaCalendario> SubcategoriaCalendario { get; set; }
	  public DbSet<SubcategoriaCalendario_Idioma> SubcategoriaCalendario_Idioma { get; set; }
	  public DbSet<Usuario> Usuario { get; set; }
	  public DbSet<CategoriaFoto> CategoriaFoto { get; set; }
	  public DbSet<CategoriaFoto_Idioma> CategoriaFoto_Idioma { get; set; }
	  public DbSet<Foto> Foto { get; set; }
	  public DbSet<Foto_Idioma> Foto_Idioma { get; set; }
	  public DbSet<SolicitudContacto> SolicitudContacto { get; set; }
	  public DbSet<Video> Video { get; set; }
	  public DbSet<Video_Idioma> Video_Idioma { get; set; }
	  public DbSet<Marca> Marca { get; set; }
	  public DbSet<Evento> Evento { get; set; }
	  public DbSet<Evento_Idioma> Evento_Idioma { get; set; }
	  public DbSet<TipoEvento> TipoEvento { get; set; }
	  public DbSet<TipoEvento_Idioma> TipoEvento_Idioma { get; set; }
	  public DbSet<CategoriaCalendario> CategoriaCalendario { get; set; }
	  public DbSet<CategoriaCalendario_Idioma> CategoriaCalendario_Idioma { get; set; }
	  public DbSet<TipoColeccionCalendario> TipoColeccionCalendario { get; set; }
	  public DbSet<TipoColeccionCalendario_Idioma> TipoColeccionCalendario_Idioma { get; set; }
	}
}
